version: "3"

services:
  postgres:
    image: postgres:13-alpine
    container_name: posts_postgres
    environment: 
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=posts
    ports:
      - 5432:5432
    volumes:
      - ./data/postgres:/var/lib/postgresql/data

  app:
    build: .
    container_name: posts_app
    ports:
      - 3333:80
      - 80:80
    environment:
      - DB_HOST=postgres
      - SERVER_PORT=80
    volumes:
      - ./src:/app/src
      - ./node_modules:/app/node_modules
    links:
      - postgres
    depends_on: 
      - postgres

